# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19064a2413d70d264771a54c6a20e53b9539ea88f6e1210b565f68c3d0605d8b79de450b88df4ceb14b03836826ae10f9040d78701722d007426e5c9cdfebcef

test:
  secret_key_base: 1f578e1a9c28406bfdee7e3410f2a398d8ad0dc571130cdd05043f662f8bc7d44bbb8de5403592bbef71213db8b52b60236b70992475139cd5edbb1b0dea9611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
